### ISSUE TITLE
Bare ccmake on minc-toolkit-v2 develop-1.9.17 errors on OpenBlas

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#72]
Trying to do an interactive ccmake against develop-1.9.17 throws this error on configure.

```
 CMake Warning at CMakeLists.txt:541 (FIND_PACKAGE):
   By not providing "FindOpenBLAS.cmake" in CMAKE_MODULE_PATH this project has
   asked CMake to find a package configuration file provided by "OpenBLAS",
   but CMake did not find one.

   Could not find a package configuration file provided by "OpenBLAS" with any
   of the following names:

     OpenBLASConfig.cmake
     openblas-config.cmake

   Add the installation prefix of "OpenBLAS" to CMAKE_PREFIX_PATH or set
   "OpenBLAS_DIR" to a directory containing one of the above files.  If
   "OpenBLAS" provides a separate development package or SDK, be sure it has
   been installed.
```

This is avoided if initial configure turns on openblas with a ``-DMT_BUILD_OPENBLAS:BOOL=ON``. I think that indicates that something is trying to include it always.

I suspect this is BeAST?

**Comment by vfonov** [comment]
BEaST supposed to be able to run without OpenBLAS , but without sparse mode (experimental anyway)

**Comment by vfonov** [comment]
https://github.com/vfonov/patch_morphology - also uses openBLAS

**Comment by vfonov** [comment]
https://github.com/vfonov/patch_morphology/blob/develop/CMakeLists.txt#L13

**Comment by gdevenyi** [comment]
Okay, probably a bug against the cmake config of patch_morpholgy then.

**Comment by vfonov** [comment]
I think i fixed this: https://github.com/BIC-MNI/minc-toolkit-v2/commit/6f789cc39b4b5f68a73eea005d51952580386823

**Comment by gdevenyi** [comment]
Bare configure still throws a warning:
```
OpenBLAS_DIR=
CMake Warning at CMakeLists.txt:545 (FIND_PACKAGE):
  By not providing "FindOpenBLAS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenBLAS",
  but CMake did not find one.

  Could not find a package configuration file provided by "OpenBLAS" with any
  of the following names:

    OpenBLASConfig.cmake
    openblas-config.cmake

  Add the installation prefix of "OpenBLAS" to CMAKE_PREFIX_PATH or set
  "OpenBLAS_DIR" to a directory containing one of the above files.  If
  "OpenBLAS" provides a separate development package or SDK, be sure it has
  been installed.
```

But the configure no longer errors out, and I can build afterwards. So, half fixed?

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.17/cmake-modules/BuildPatchMorphology.cmake#L45 - this is supposed to instruct CMAKE not to look for OpenBLASConfig.cmake and use OpenBLAS_INCLUDE_DIR / OpenBLAS_LIBRARY

**Comment by gdevenyi** [comment]
builds and tests pass with and without openblas in superbuild. Only issue is that if you configure without and then enable afterwards the superbuild openblas doesn't get detected.
